### ISSUE TITLE
Just a Question?

### ISSUE THREAD

**Issue by UltraHispeed-Elite** [DirtPowered/DirtMultiversion#32]
Does DirtMultiversion work with the Geyser Proxy for Bedrock Crossplay?

**Comment by EditChris** [comment]
Yes, it works, I have that setup in my server, but players can't access it anymore because we need this to update to 1.19.4. But when we were on the previous version it did work, and you could even fly perfectly using the creative mode on Bedrock, without any need of the Magic Carpet plugin.
