### ISSUE TITLE
Error when right clicking [unstable]

### ISSUE THREAD

**Issue by candrawardana** [DirtPowered/DirtMultiversion#5]
kick error when clicking with newer version (above 1.8). and cannot crafting with geyser support

**Comment by outofmem13** [comment]
What server version? and what kick message

**Comment by candrawardana** [comment]
server version craft bukkit 1.0.0 with lastest compiled DirtMV

kick message : none

client : 1.16.5 (via version enabled)

**Comment by outofmem13** [comment]
Fixed.
About geyser issues - as for now I don't know how to fix them

**Comment by candrawardana** [comment]
yes it's does fix the crafting shift + click item

but in chest, inventory, furnance etc it doesn't

i suggest disable shift entirely like disable hold right click when crafting

**Comment by candrawardana** [comment]
i send my server ip in discord, (i am Cardana Mine Hero). if you wanna check my setup

**Comment by outofmem13** [comment]
From my testing - chests are working correctly. Shift-clicking in furnaces was introduced in 1.2.5
Looks like you're not running latest DMV on your server.

https://user-images.githubusercontent.com/30810750/108337985-0a9e0400-71d6-11eb-928a-e491006cc4be.mp4

**Comment by candrawardana** [comment]
awesome! my bad, i forgot to recompile
