### ISSUE TITLE
1.2.1 - 1.7.10 cannot render chunks

### ISSUE THREAD

**Issue by candrawardana** [DirtPowered/DirtMultiversion#6]
![image](https://user-images.githubusercontent.com/38995778/108355498-7ce60700-721d-11eb-8e50-19704e459207.png)

Server version : craftbukkit 1.0.0

client within 1.2.1 to 1.7.10 cannot render world, but in >=1.8 or <=1.1 it works properly

**Comment by outofmem13** [comment]
Fixed

**Comment by candrawardana** [comment]
WHOA awesome!!!

now this proxy is very very very stable right now

no random kick, no chunk render issues, i guess we need to get the release packages!. so anyone no longer need to compile, just plug n play!
