### ISSUE TITLE
cows changing size in upper version (1.16) with 1.0.0 server

### ISSUE THREAD

**Issue by candrawardana** [DirtPowered/DirtMultiversion#7]
![image](https://user-images.githubusercontent.com/38995778/108449679-734cb580-7296-11eb-8251-efe700a61b0e.png)
![image](https://user-images.githubusercontent.com/38995778/108449762-9bd4af80-7296-11eb-9768-674329afe3b2.png)

cows becames adult and then becames child again

maybe other entities too

**Comment by outofmem13** [comment]
Should be fixed

**Comment by candrawardana** [comment]
nice
