### ISSUE TITLE
b1.7.3 server non-joinable

### ISSUE THREAD

**Issue by RedLeader167** [DirtPowered/DirtMultiversion#9]
Tried to join 1.7.3 beta server using 1.12.2, 1.9, 1.8, 1.7.10, 1.0, b1.8, but every version is not working. I seeing world for lil bit but then negativearrayexception or 56 packet length error. IP of the server is play.rubeta.net, port 25565. (tried to use jar from release and compiled by me, but results are same)

P.S. sorry for my english, im russian.

**Comment by RaphiMC** [comment]
Can confirm that it doesn't work with DMV

**Comment by outofmem13** [comment]
I'll take a look at that. Interesting
